services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Password@123
      - DB_NAME=SUPATRA_WEEK13

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: SUPATRA_WEEK13
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  time_network:
    driver: bridge